
name: Bitwarden官方11个独立镜像

on:
  workflow_dispatch:
    # Inputs the workflow accepts.



# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-chengdu
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: tickg
  IMAGE: "${{ github.event.inputs.image }}"
  TAG: "${{ github.event.inputs.tag }}"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: push_to_aliyun
    
    steps:  
    
    # 1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1.0.6
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        #login-server: "${{ env.REGISTRY }}"
        #username: "${{ secrets.USERNAME }}"
        #password: "${{ secrets.PASSWORD }}"
        
    # 2 Build and push image to ACR
    - name: Build and push image to ACR
      run: |
        echo curdir=$(pwd)
        echo sysinfo=$(uname -a)
        echo whoami=$(whoami)
        echo IMAGE=${{ env.IMAGE }}
        echo TAG=${{ env.TAG }}
        
        docker pull bitwarden/mssql:latest
        docker pull bitwarden/web:latest
        docker pull bitwarden/attachments:latest
        docker pull bitwarden/api:latest
        docker pull bitwarden/identity:latest
        docker pull bitwarden/sso:latest
        docker pull bitwarden/admin:latest
        docker pull bitwarden/icons:latest
        docker pull bitwarden/notifications:latest
        docker pull bitwarden/events:latest
        docker pull bitwarden/nginx:latest
        
        docker images
        
        REGISTRY="registry.cn-chengdu.aliyuncs.com"
        NAMESPACE=tickg
        
        docker tag  bitwarden/mssql:latest           "$REGISTRY/$NAMESPACE/bitwarden-mssql:latest"
        docker tag  bitwarden/web:latest             "$REGISTRY/$NAMESPACE/bitwarden-web:latest"
        docker tag  bitwarden/attachments:latest     "$REGISTRY/$NAMESPACE/bitwarden-attachments:latest"
        docker tag  bitwarden/api:latest             "$REGISTRY/$NAMESPACE/bitwarden-api:latest"
        docker tag  bitwarden/identity:latest        "$REGISTRY/$NAMESPACE/bitwarden-identity:latest"
        docker tag  bitwarden/sso:latest             "$REGISTRY/$NAMESPACE/bitwarden-sso:latest"
        docker tag  bitwarden/admin:latest           "$REGISTRY/$NAMESPACE/bitwarden-admin:latest"
        docker tag  bitwarden/icons:latest           "$REGISTRY/$NAMESPACE/bitwarden-icons:latest"
        docker tag  bitwarden/notifications:latest   "$REGISTRY/$NAMESPACE/bitwarden-notifications:latest"
        docker tag  bitwarden/events:latest          "$REGISTRY/$NAMESPACE/bitwarden-events:latest"
        docker tag  bitwarden/nginx:latest           "$REGISTRY/$NAMESPACE/bitwarden-nginx:latest"
        
        docker images
        
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-mssql:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-web:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-attachments:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-api:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-identity:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-sso:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-admin:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-icons:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-notifications:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-events:latest"
        docker push   "$REGISTRY/$NAMESPACE/bitwarden-nginx:latest"
        

        
